Chatterino/website

- public/client_login/index.html
> Added `moderator:manage:automod` scope

- pages/index.js
Removes the note about JOIN rate-limits. I was able to join 139 channels no problem.
> Remove note about join rate-limiting as it's no longer needed.

- pages/client_login.js
> chore: request raids scope on login

- pages/client_login.js
For https://github.com/Chatterino/chatterino2/issues/4019
> chore: add helix chatters scope

- .env.development
- .env.production
- pages/client_login.tsx
This can be configured by users with an `.env.local` file
See https://nextjs.org/docs/basic-features/environment-variables
> Load Redirect URL & Client ID from environment files

- pages/client_login.tsx
- hide the text input by default
- revert clientid & redirect
- Load Redirect URL & Client ID from environment files (#109)
Original PR #105 by @gempir :bow:
> pretty secret

- pages/client_login.tsx
From the twitchdev stream today, the docs link does NOT currently work for me, but other say it does 
https://dev.twitch.tv/docs/api/reference#update-shield-mode-status 
Also might be possible that there's 2 docs for it, one for get and one for update, but I can't check yet.
> Add shield-mode scopes

- pages/client_login.tsx
Relies on https://github.com/Chatterino/chatterino2/pull/4117 which will probably be merged on Sunday
> Update `moderator:read:chatters` comment

- links.ts
- pages/changelog.mdx
- Update website for v2.4.3 release
- Update `#4577` changelog (#184)
- Update pages/changelog.mdx
> Update website for v2.4.3 release

- .editorconfig
- .gitattributes
- remove eol in .gitattrubtes
- add editorconfig
> Undo gitattributes change & add editorconfig file

- pages/changelog.mdx
I thought about doing it before I approved it, but then I forgot
> Add 2.4.4 release date to the changelog

- package.json
Minimum required node version: v16
Yarn v1
> chore: Specify node & yarn version in package.json

- pages/client_login.tsx
Required for https://github.com/Chatterino/chatterino2/issues/5127
> chore(login): add helix send chat message scope

- pages/client_login.tsx
- **add user:read:emotes scope**
- **update some old scope comments**
> chore: add read emotes scope

- links.ts
- **Update version to 2.5.0**
- **Remove Windows-specific version & download URLs**
> Release v2.5.0

- links.ts
- pages/changelog.mdx
Pending https://github.com/Chatterino/chatterino2/pull/5364 merge & artifact upload
> Release v2.5.1

- package.json
- yarn.lock
Co-authored-by: @brian6932 
Replacement for https://github.com/Chatterino/website/pull/473
> fix: pnpm/next dependency error

- pages/client_login.tsx
https://github.com/Chatterino/chatterino2/issues/5439
> chore: add warnings scope

- pages/client_login.tsx
See https://github.com/Chatterino/chatterino2/pull/5239 for the reason this is needed.
> feat: add `user:read:follows` scope

- components/credit.tsx
- components/figure-group.tsx
- components/figure.tsx
- components/section.tsx
- next.config.mjs
- pages/changelog.mdx
- styles/globals.css
I love reinventing the wheel, so this adds some more styling to make the changelog more readable.
> chore: add more style to the changelog

- next.config.mjs
- package.json
- styles/globals.css
- yarn.lock
Adds a `#` after a heading with an ID and fixes the scroll-offset.
> chore: improve headings

- pages/linux.tsx
This should guide users in the right direction until https://github.com/flathub/flathub/issues/4767 is resolved.
> Add note about Flathub branches on the Linux install page

- pages/linux.tsx
noble numbat(s)
i don't know if for some reason the universal repo is no longer required, this is just a copy paste job
> Add Ubuntu 24.04 deb link

- pages/client_login.tsx
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelmoderate-v2
> Add missing scopes for `channel.moderate` eventsub topic

- pages/client_login.tsx
this is required for eventsub work we're doing
https://github.com/Chatterino/chatterino2/pull/6007/files
> feat: add `moderator:read:suspicious_users` scope

- links.ts
To be merged in when fourtf has received & uploaded the binaries & updated notitia
> Update links for v2.5.3 release

- links.ts
Pending fourtf's binary upload
> Release v2.5.4
