Chatterino/website

.github/workflows/deploy.yml

According to [node release schedule](https://nodejs.org/en/about/releases/), v15 is no longer supported. Instead, I figured that moving to LTS version is probably the best call.

Bump nodejs version in deploy action

---

next.config.js
pages/client_login.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

tailwind.config.js

- darkMode is now enabled by default
https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
- purge key changed to content due to Tailwind not using PurgeCSS under the hood
https://tailwindcss.com/docs/upgrade-guide#configure-content-sources
- gray scales have been renamed, trueGray is now called neutral
https://tailwindcss.com/docs/upgrade-guide#renamed-gray-scales

Fix Tailwind v3 deprecations

---

pages/client_login.js

These are broadcaster-scoped, so only really useful for the broadcaster.

Request scopes for managing & reading polls

---

pages/client_login.js

Adds `moderator:manage:announcements` for a future /announce color options possibility. Adds `user:manage:whispers` so now new-ish (post-2019) users can send whispers maybe (except they have to give up their data).

Add announce and whispers API scopes

---

pages/client_login.tsx

This PR does the following:
1. Drops Kraken/Helix scopes that have been removed by Twitch: c03c82b
2. Adds comments to the scopes that were missing them: d2c32b6
3. Updates the comments for scopes soon to be deprecated: 28d4ba2
4. Adds comments stating which scopes are currently unused: ff34972
5. Updates a few existing comments: 7b55d8e
6. Adds Twitch documentation links to comments: a9e4817 bfeb344
Here's a side-by-side: that might be easier to read than all commits together:
https://github.com/chatterino/website/blob/main/pages/client_login.tsx
https://github.com/Felanbird/website/blob/chore/cleanup-scopes/pages/client_login.tsx
`channel:read:redemptions`
According to the [pubsub docs](https://dev.twitch.tv/docs/pubsub#available-topics): You are required to have this scope paired with …

Update & Cleanup scopes

---

pages/index.tsx
tailwind.config.js

This solves #139 
<details><summary>Hero section</summary>
<table align="center">
<tr>
<th>Original</th>
<th>Changed</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</details>
<details><summary>Testimonials section</summary>
<table align="center">
<tr>
<th>Original</th>
<th>Changed</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</details>
<details><summary>Miscellaneous section</summary>
<table align="center">
<tr>
<th>Original</th>
<th>Changed</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</details>
- Added custom "xs" screen breakpoint to tailwind config
- On narrow screens:
- Adjusted paddings and margins to fit more content
- Chat component:
- Scaled to 75%
- Testimonial component:
- Changed flex-direction to column
- Centered avatar
- Miscellaneous component:
- …

Improve home page on mobile

---

pages/index.tsx
styles/globals.css

There are currently a couple of issues with the Carousel component that can make it uncentered in the page:
- It overflows it's container when at max width.
- When it is shrunk due to page resizing, the .carrousel-root element can be wider than .carrousel.
- Removed max-width from the Section's styling to prevent overflow.
- Centered the .carousel element.

Fix Carousel centering

---

pages/client_login.tsx

I just noticed yesterday that there is a beta API for sending Shoutouts and 2 EventSub Topics.
From my research it seems like you have to use the `moderator:manage:shoutouts` scope for the send a shoutout endpoint but you can optionally also use `moderator:read:shoutouts` for the EventSub Topics.
I just added the manage scope (I took the shield mode PR as template on how to) because I do not know if we really need  both because the manage seems to have all capabilities that the read scope has.
References:
[API Endpoint for sending a Shoutout](https://dev.twitch.tv/docs/api/reference/#send-a-shoutout)
[channel.shoutout.create EventSub subscription type](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelshoutoutcreate)
[channel.shoutout.receive EventSub subscription …

Added Shoutout Scope

---

pages/client_login.tsx

I noticed them when linking someone the scope list we request

Remove deprecated IRC command scopes

---

pages/changelog.mdx

Older ones are takes either from the GitHub Release date or from my own copies. Generally they should only differ by a week max.

Add dates to the changelog

---

links.ts
pages/linux.tsx

Fixes #208
We link to the GitHub release here
AppImage portion was moved down where it belongs

Add Ubuntu deb links & move AppImage down

---

links.ts
pages/changelog.mdx

This release is a security release for Windows only
I haven't fixed anything in `download.tsx` so the download links to non-windows-builds there will be broken, but I don't want to make this PR too big.
The release can be found here https://github.com/Chatterino/chatterino2/releases/tag/v2.4.6

Release v2.4.6 (Windows only)

---

pages/changelog.mdx

This PR includes a fix for a typo I noticed (Window 7) and something Felanbird noticed and mentioned in pajlada's Twitch Channel at 00:23:15, 00:23:44 and 00:23:48 germany time.

Fix typos in `changelog.mdx`

---

pages/client_login.tsx

This is required for some EventSub subscriptions. I tested this by manually adding the scope to the chatterino login page, and everything works as expected.

Add user:chat:read scope

---

pages/client_login.tsx

Useful if we switch to anon irc read connections or eventsub chat (as these approaches don't deliver `USERSTATE` with mod status information)
Alternatively, could be used (by a plugin?) to provide a handy button to join all channels that the user moderates

chore(login): request moderated channels scope

---

components/chat/common.js

Uses `Intl.DateTimeFormatter` to format the local time. Previously, the UTC time was displayed.

fix: use local time in chat component

---

components/credit.tsx

`[]` is truthy in JS, so `[] && foo` is always `foo`.

fix: remove empty "with help from"

---

pages/linux.tsx

Now that https://github.com/flathub/flathub/issues/4767 is finally resolved, the note that was added in #631 should be removed.

Revert "Add note about Flathub branches on the Linux install page"

---

components/figure-group.tsx
pages/changelog.mdx
styles/globals.css

- Reduce spacing in figures (the author attribution had more space above than below)
- Mention that PubSub ends in mid april
- Chatterino could crash if a request was made _from a coroutine_ (or interacted with it).
- Misc changes are more important than fixes
- Mention that Qt 5 will no longer be supported
- Turn last paragraph into a list like the other entries

chore: misc changes to the changelog

---

styles/globals.css

Sometimes, just the text on the Chatterino website takes long to load (probably when it's not cached). We can use `font-display: swap` to use a fallback font sooner.
See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display).
Epic GitHub-Web commit.

fix: use `font-display: swap`
